"use client";
import { useEffect, useMemo, useState } from "react";
type Project={id:string;title:string;logline:string;genre:string}; type Block={id:string;act:number;kind:string;title:string;body:string;sortOrder:number}; type Item={id:string;kind:string;title:string;body:string;meta:string};
const baseActs=["1막 · 각성","2막 · 진실과 갈등","3막 · 결전과 선택"];
export function Storyyard({userName}:{userName:string}){
 const[projects,setProjects]=useState<Project[]>([]);const[activeId,setActiveId]=useState<string|null>(null);const[blocks,setBlocks]=useState<Block[]>([]);const[items,setItems]=useState<Item[]>([]);const[tab,setTab]=useState("plot");const[loading,setLoading]=useState(true);const[dragged,setDragged]=useState<string|null>(null);const[docId,setDocId]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/projects").then(r=>r.json()).then(d=>{setProjects(d.projects||[]);setActiveId(d.projects?.[0]?.id||null);setLoading(false);});},[]);
 useEffect(()=>{if(!activeId)return;fetch(`/api/projects/${activeId}/blocks`).then(r=>r.json()).then(d=>setBlocks(d.blocks||[]));fetch(`/api/projects/${activeId}/items`).then(r=>r.json()).then(d=>{setItems(d.items||[]);setDocId(d.items?.find((x:Item)=>x.kind==="document")?.id||null);});},[activeId]);
 const active=projects.find(p=>p.id===activeId);const chars=items.filter(x=>x.kind==="character");const docs=items.filter(x=>x.kind==="document");const byAct=useMemo(()=>baseActs.map((name,i)=>({name,act:i+1,blocks:blocks.filter(b=>b.act===i+1).sort((a,b)=>a.sortOrder-b.sortOrder)})),[blocks]);
 async function createProject(){const title=prompt("작품 제목","새 작품");if(!title)return;const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title})});const d=await r.json();if(d.project){setProjects(x=>[d.project,...x]);setActiveId(d.project.id);}}
 async function addBlock(act:number){if(!activeId)return;const r=await fetch(`/api/projects/${activeId}/blocks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({act,title:"새 블록",body:"이 장면에서 벌어지는 일을 적어."})});const d=await r.json();if(d.block)setBlocks(x=>[...x,d.block]);}
 async function editBlock(b:Block){const title=prompt("블록 제목",b.title);if(title===null)return;const body=prompt("블록 내용",b.body);if(body===null)return;const next={...b,title:title||b.title,body};setBlocks(x=>x.map(v=>v.id===b.id?next:v));await fetch(`/api/blocks/${b.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(next)});}
 async function move(act:number){const b=blocks.find(x=>x.id===dragged);if(!b||b.act===act)return setDragged(null);setBlocks(x=>x.map(v=>v.id===b.id?{...v,act,sortOrder:Date.now()}:v));setDragged(null);await fetch(`/api/blocks/${b.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({act,sortOrder:Date.now()})});}
 async function addItem(kind:string){if(!activeId)return;const title=prompt(kind==="character"?"인물 이름":"문서 제목",kind==="character"?"새 인물":"새 문서");if(!title)return;const body=kind==="character"?(prompt("역할과 설명","")??""):"";const r=await fetch(`/api/projects/${activeId}/items`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,title,body})});const d=await r.json();if(d.item){setItems(x=>[...x,d.item]);if(kind==="document")setDocId(d.item.id);}}
 async function saveItem(item:Item){setItems(x=>x.map(v=>v.id===item.id?item:v));await fetch(`/api/items/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(item)});}
 if(loading)return <main className="loading-shell">작업판 불러오는 중…</main>;
 if(!active)return <Empty onCreate={createProject}/>;
 const doc=docs.find(x=>x.id===docId);
 return <main className="studio-shell"><aside className="sidebar"><div className="brand">STORYYARD</div><div className="profile">{userName}</div><button className="new-work" onClick={createProject}>＋ 새 작품</button><p className="side-label">내 작품</p>{projects.map(p=><button key={p.id} className={p.id===activeId?"project-link active":"project-link"} onClick={()=>setActiveId(p.id)}><strong>{p.title}</strong><small>{p.genre}</small></button>)}</aside><section className="workspace"><header className="workspace-header"><div><p className="eyebrow">개인 작업실</p><h1>{active.title}</h1><p>{active.logline}</p></div><div className="view-switch">{["plot","characters","documents"].map(x=><button key={x} className={tab===x?"selected":""} onClick={()=>setTab(x)}>{x==="plot"?"플롯":x==="characters"?"등장인물":"문서"}</button>)}</div></header>{tab==="plot"&&<section className="plot-board">{byAct.map(a=><article key={a.act} className="act-column" onDragOver={e=>e.preventDefault()} onDrop={()=>move(a.act)}><div className="act-head"><button onClick={()=>alert("막 제목/설명 편집은 다음 패치에서 인라인 편집으로 넣음. 지금은 블록부터 쓰면 됨.")}>{a.name}</button><em>{a.blocks.length}</em></div><p className="act-prompt">막 제목을 눌러 편집 준비 상태를 확인할 수 있음.</p><div className="block-stack">{a.blocks.map(b=><button key={b.id} draggable onDragStart={()=>setDragged(b.id)} onClick={()=>editBlock(b)} className="plot-card"><strong>{b.title}</strong><span>{b.body}</span></button>)}</div><button className="add-block" onClick={()=>addBlock(a.act)}>＋ 새 블록</button></article>)}</section>}{tab==="characters"&&<section className="panel"><div className="section-toolbar"><h2>등장인물</h2><button className="primary-button" onClick={()=>addItem("character")}>＋ 새 인물</button></div><div className="character-grid">{chars.map(c=><button className="character-card" key={c.id} onClick={()=>{const body=prompt("인물 설명",c.body);if(body!==null)saveItem({...c,body});}}><strong>{c.title}</strong><p>{c.body||"역할·욕망·관계를 적어."}</p></button>)}</div></section>}{tab==="documents"&&<section className="documents-view"><aside className="document-list"><button className="add-document" onClick={()=>addItem("document")}>＋ 새 문서</button>{docs.map(d=><button className={d.id===docId?"active":""} key={d.id} onClick={()=>setDocId(d.id)}>{d.title}</button>)}</aside>{doc?<Editor item={doc} save={saveItem}/>:<div className="document-empty">새 문서를 만들면 여기서 바로 쓸 수 있음.</div>}</section>}</section></main>;
}
function Editor({item,save}:{item:Item;save:(x:Item)=>void}){const[draft,setDraft]=useState(item);return <div className="document-editor"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} placeholder="설정, 장면, 메모를 쓴다."/><button className="primary-button" onClick={()=>save(draft)}>저장</button></div>}
function Empty({onCreate}:{onCreate:()=>void}){return <main className="empty-state"><p className="eyebrow">STORYYARD</p><h1>첫 작품부터 깔자.</h1><button className="primary-button" onClick={onCreate}>새 작품 만들기</button></main>}
